#!/usr/bin/env python

# This is a script which uses Terpdose to plot the arrays generated by the ScatterMMS.f90 driver

import numpy as np
import matplotlib.pyplot as plt
import Terpdose as td
from Terpdose import *

fname = 'ScatterMMS.h5'

D = Lionbolt (fname)

mesh = D.mesh

c  = mesh.connectivity ()
o  = mesh.offset       ()
rg = mesh.nodes        ()

exact = D.exact.angular_fluence ()
phi_exact = exact[0].fluence ()

virtual = D.virtual.angular_fluence ()
phi_virtual = virtual[0].fluence ()

# geo  = Plane ( n=[30, 30], origin=[0.0, 0.0, 0.0], ax1=[1.0, 0.0, 0.0], ax2=[0.0, 1.0, 0.0] )

# arr_exact   = GeoInterpolation (mesh, geo, phi_exact)
# arr_virtual = GeoInterpolation (mesh, geo, phi_virtual)

# fig, ax = plt.subplots()
# im = ax.imshow(arr_exact, cmap='jet', interpolation='nearest')
# ax.set_title('exact')
# fig.colorbar(im, ax=ax, label='Value')
# plt.show()

# fig, ax = plt.subplots()
# im = ax.imshow(arr_virtual, cmap='jet', interpolation='nearest')
# ax.set_title('virtual')
# fig.colorbar(im, ax=ax, label='Value')
# plt.show()

geo  = Line ( n=100, x0=[0.0, 0.0, -1.0], x1=[0.0, 0.0, 1.0] )

arr_exact   = GeoInterpolation (mesh, geo, phi_exact)
arr_virtual = GeoInterpolation (mesh, geo, phi_virtual)

u = np.array([np.dot(geo.xyz[i,:], geo.ehat) for i in range(geo.n)])

fig, ax = plt.subplots(figsize=(7.1, 4))

ax.plot (u, arr_exact, '-', markersize=0.0, linewidth=0.75, color='blue')
ax.plot (u, arr_virtual, '-', markersize=0.0, linewidth=0.75, color='red')

plt.show()