#!/usr/bin/env python

# This is a script which uses Terpdose to plot the arrays generated by the ScatterMMS.f90 driver

import numpy as np
import matplotlib.pyplot as plt
from Terpdose import *

fname = 'TransportMMS.h5'

D = Lionbolt (fname)

mesh = D.mesh

c  = mesh.connectivity ()
o  = mesh.offset       ()
rg = mesh.nodes        ()

exact = D.exact.angular_fluence ()
phi_exact = exact[0].fluence ()

virtual = D.virtual.angular_fluence ()
phi_virtual = virtual[0].fluence ()

geo  = Plane ( n=[500, 500], origin=[0.0, 0.0, 0.0], ax1=[1.0, 0.0, 0.0], ax2=[0.0, 1.0, 0.0] )

arr_exact   = GeoInterpolation (mesh, geo, phi_exact)
arr_virtual = GeoInterpolation (mesh, geo, phi_virtual)

fig, ax = plt.subplots()
im = ax.imshow(arr_exact, cmap='jet', interpolation='nearest')
ax.set_title('exact')
fig.colorbar(im, ax=ax, label='Value')
plt.show()

fig, ax = plt.subplots()
im = ax.imshow(arr_virtual, cmap='jet', interpolation='nearest')
ax.set_title('virtual')
fig.colorbar(im, ax=ax, label='Value')
plt.show()

fig, ax = plt.subplots()
im = ax.imshow(arr_exact - arr_virtual, cmap='jet', interpolation='nearest')
ax.set_title('diff')
fig.colorbar(im, ax=ax, label='Value')
plt.show()