Module Sources
    use constants
    use Geometry
    use AngularSpace
    Implicit None
    Private
    
    ! I could use a build routine very smartly here, to create potentially everything,
    ! including the fluence. But certainly to fold together FieldGeometry and ExternalBeam.
    ! Just have ExternalBeam initialize like FieldGeometry, and turn ExternalBeam's
    ! initialization to Build routines.
    ! YES. DO THIS. If not now then in first update.
    ! Should look everywhere for places I can use Build routines.
    
    Type FieldGeometry
        ! This class defines the abstract geometric character of a beam, 
        ! independent of the problem discretization.
        ! 
        ! Contains InField, which, if given a point r,
        ! it tells you whether or not the point is in the beam
        Logical                        :: slab               ! Whether or not this is a slab-based source
        Real (KREAL)                   :: weight             ! Scaling factor for the particles in the beam. Beam units are generally in 'per particle' but with multiple beams you must scale them relatively using this
        Real (KREAL)                   :: span               ! Either the area of the field cross section (for planar beams) or the solid angle (for spherical beams)
        Real (KREAL)                   :: origin       (3)   ! Origin of the incident field (important if angular = spherical)
        Real (KREAL)                   :: axis         (3)   ! Central axis of the incident field, direction describing the direction of particles.
        Real (KREAL)                   :: e1           (3)   ! Beam-frame x vector
        Real (KREAL)                   :: e2           (3)   ! Beam-frame y vector
        Real (KREAL)                   :: cutoutparams (4)   ! Linac cutout parameters ! MAY NOT BE NEEDED OUTSIDE OF INPUT, KEEPING IN CASE I DO SOME STUFF WITH MANUALLY FINDING NODES IN BEAM
        Character (LEN=:), Allocatable :: cutout             ! Field cutout shape (none, circle, rectangle). Later on users will be able to enter a filename with a 2D loop described by mesh points
        Character (LEN=:), Allocatable :: angdist            ! Angular distribution of field ('spherical', 'planar')
        Character (LEN=:), Allocatable :: spectrum           ! A file (OR the string 'flat') specifying what the field's energy spectrum is
    Contains
        Procedure :: InField
        Procedure :: Destroy => DestroyField
    End Type
    
    Interface FieldGeometry
        Module Procedure init_FieldGeometryGen
        Module Procedure init_FieldGeometrySlab
    End Interface
    
    Type BeamRay
        ! Defines a ray, i.e., the quantity of interest
        ! when ray-tracing. It gives all of the information for which
        ! we ray-trace in the first place --- the path length
        ! through a given material, as well as addressing information.
        Integer                   :: q           ! Quadrature sdof index of this ray
        Real (KREAL), Allocatable :: pathlen (:) ! Path length this ray endures within each material ! (m)
    End Type
    
    Type ExternalBeam
        ! The actual implementation of a beam in the context of Boltzmann transport.
        ! Contains, most importantly, a set of type-bound procedures that are
        ! relied upon in order to construct usable sources derived from external beams,
        ! that can thus be fed to a Boltzmann operator for a solution
        Logical,             Allocatable :: quadmask (:)   ! Tells if a quadrature point is in the beam ! (qdof)
        Logical,             Allocatable :: elemmask (:)   ! Tells if an element is in the beam         ! (e)
        Real (KREAL)                     :: n = ONE        ! Number of particles in this beam
        Real (KREAL),        Allocatable :: phi0s    (:)   ! Uncollided fluence, spatial profile ONLY   ! (qdof)
        Character (LEN=:),   Allocatable :: particle       ! Name of particle generated by this beam ! Is this actually useful? Leaving it in for user-friendliness
        Type (MeshClass),    Pointer     :: mesh
        Type (AngularClass), Pointer     :: angular
        Type (FieldGeometry)             :: fldgeo
        Type (BeamRay),      Allocatable :: rays     (:)   ! Rays, generated via self%RayTrace, that can be used to construct a primary angular fluence if desired
    Contains
        Procedure :: Populate
        Procedure :: GenerateENSRCFile
        Procedure :: RayTrace
        Procedure :: PrepFluence       ! Mostly internal routine for preparing the spatial part of the fluence map for fluence quad
        Procedure :: FluenceQuadrature ! Mostly internal routine, gives the fluence at mesh quadrature points
        Procedure :: AddAngularFluence ! A subroutine that adds the (uncollided) angular fluence on the real mesh. I hate it
        Procedure :: Source  => FCSSource ! Rename to AddSource? That's what it does...
        Procedure :: Destroy => DestroyBeam
    End Type
    
    Interface ExternalBeam
        Module Procedure init_ExternalBeam
    End Interface
    
    Integer                   :: Lcoeff      ! Also private
    Real (KREAL), Allocatable :: coeff (:,:) ! Private so no concern about naming and such
    
    Public :: FieldGeometry, BeamRay, ExternalBeam, GenAngularDistribution, SlabAngularDistribution, &
              InitializeLegendreCoefficients, DestroyLegendreCoefficients
    
    Interface
        
        Module Function init_FieldGeometryGen (weight, spectrum, origin, axis, angdist, cutout, cutoutparams) Result (self)
            use constants
            use IO
            use BasicMathFunctions
            Implicit None
            Real (KREAL),        Intent (In) :: weight
            Character (*),       Intent (In) :: spectrum
            Real (KREAL),        Intent (In) :: origin       (3)
            Real (KREAL),        Intent (In) :: axis         (3)
            Character (*),       Intent (In) :: angdist
            Character (*),       Intent (In) :: cutout
            Real (KREAL),        Intent (In) :: cutoutparams (:)
            Type (FieldGeometry)             :: self
        End Function
        
        Module Function init_FieldGeometrySlab (weight, spectrum, angle) Result (self)
            use constants
            Implicit None
            Real (KREAL),        Intent (In) :: weight
            Character (*),       Intent (In) :: spectrum
            Real (KREAL),        Intent (In) :: angle
            Type (FieldGeometry)             :: self
        End Function
        
        Module Function InField (self, r) Result (l)
            use constants
            use IO
            use BasicMathFunctions
            Implicit None
            Class (FieldGeometry), Intent (In) :: self
            Real (KREAL),          Intent (In) :: r (3)
            Logical                            :: l
        End Function
        
        Module Function init_ExternalBeam (mesh, angular, fldgeo, particle) Result (self)
            use constants
            use IO
            use BasicMathFunctions
            use Quadrature
            use Geometry
            use AngularSpace
            Implicit None
            Type (MeshClass),     Target, Intent (In) :: mesh
            Type (AngularClass),  Target, Intent (In) :: angular
            Type (FieldGeometry),         Intent (In) :: fldgeo
            Character (*),                Intent (In) :: particle
            Type (ExternalBeam)                       :: self
        End Function
        
        Module Subroutine Populate (self, Emin, Emax, Ei, Ef)
            use constants
            use IO
            use Interpolation
            Implicit None
            Class (ExternalBeam),   Intent (InOut) :: self
            Real (KREAL),           Intent (In)    :: Emin
            Real (KREAL),           Intent (In)    :: Emax
            Real (KREAL),           Intent (In)    :: Ei
            Real (KREAL),           Intent (In)    :: Ef
        End Subroutine
        
        Module Subroutine GenerateENSRCFile (self, energy, fname)
            use constants
            use NittanyAPI
            Implicit None
            Class (ExternalBeam), Intent (In) :: self
            Type (EnergyGrid),    Intent (In) :: energy
            Character (*),        Intent (In) :: fname
        End Subroutine
        
        Module Subroutine RayTrace (self)
            ! NOTE - this routine uses RayTracing
            ! Yet, RayTracing uses Sources. Circular dependency
            ! I didn't really expect this to compile successfully, 
            ! but it did, and it ran properly. So I'm leaving things as-is.
            ! Just keep it in mind.
            Implicit None
            Class (ExternalBeam), Intent (InOut) :: self
        End Subroutine
        
        Module Subroutine PrepFluence (self)
            use constants
            use IO
            use Quadrature
            Implicit None
            Class (ExternalBeam), Intent (InOut) :: self
        End Subroutine
        
        Module Function FluenceQuadrature (self, attn) Result (phi0q)
            use constants
            Implicit None
            Class (ExternalBeam), Intent (InOut) :: self
            Real (KREAL),         Intent (In)    :: attn  (:)
            Real (KREAL),         Allocatable    :: phi0q (:)
        End Function
        
        Module Subroutine AddAngularFluence (self, attn, unc)
            use constants
            use IO
            use Quadrature
            use ShapeFunctions
            use LinearOperatorClass
            Implicit None
            Class (ExternalBeam),     Intent (InOut) :: self
            Real (KREAL),             Intent (In)    :: attn  (:)
            Type (SpaceAngleVector),  Intent (InOut) :: unc
        End Subroutine
        
        Module Subroutine FCSSource (self, OpK, s)
            use constants
            use IO
            use Quadrature
            use Polynomials
            use ShapeFunctions
            use LinearOperatorClass
            use ScatteringOperator
            Implicit None
            Class (ExternalBeam),    Intent (InOut) :: self
            Type (ScatteringOp),     Intent (In)    :: OpK
            Type (SpaceAngleVector), Intent (InOut) :: s
        End Subroutine
        
    End Interface

Contains
    
    Subroutine DestroyField (self)
        Implicit None
        Class (FieldGeometry), Intent (InOut) :: self
        
        if (ALLOCATED(self%cutout))   DEALLOCATE(self%cutout)
        if (ALLOCATED(self%angdist))  DEALLOCATE(self%angdist)
        if (ALLOCATED(self%spectrum)) DEALLOCATE(self%spectrum)
        
    End Subroutine
    
    Subroutine DestroyBeam (self)
        Implicit None
        Class (ExternalBeam), Intent (InOut) :: self
        
        if (ALLOCATED(self%quadmask)) DEALLOCATE(self%quadmask)
        if (ALLOCATED(self%elemmask)) DEALLOCATE(self%elemmask)
        if (ALLOCATED(self%particle)) DEALLOCATE(self%particle)
        if (ALLOCATED(self%phi0s))    DEALLOCATE(self%phi0s)
        if (ASSOCIATED(self%mesh))    NULLIFY(self%mesh)
        if (ASSOCIATED(self%angular)) NULLIFY(self%angular)
        call self%fldgeo%Destroy ()
        if (ALLOCATED(self%rays))     DEALLOCATE(self%rays)
        
    End Subroutine
    
    Subroutine InitializeLegendreCoefficients (L)
        use Polynomials
        Implicit None
        Integer, Intent (In) :: L
        
        Lcoeff = L
        call LegendreCoefficients (L, coeff)
        
    End Subroutine
    
    Subroutine DestroyLegendreCoefficients ()
        Implicit None
        
        Lcoeff = 0
        DEALLOCATE(coeff)
        
    End Subroutine
    
    Function GenAngularDistribution (k, k0) Result (f)
        use BasicMathFunctions
        use Polynomials
        Implicit None
        Real (KREAL), Intent (In) :: k  (3)
        Real (KREAL), Intent (In) :: k0 (3)
        
        Real (KREAL)              :: f
        
        Integer                   :: ell
        Real (KREAL)              :: kk0
        
        kk0 = DOT_PRODUCT(k, k0)
        
        f = ZERO
        do ell = 0, Lcoeff
            f = f + (2 * ell + 1) * SimpleHorner (x=kk0, c=coeff(ell,0:ell)) / FOURPI
        end do
        
    End Function
    
    Function SlabAngularDistribution (mu, mu0) Result (f)
        use BasicMathFunctions
        use Polynomials
        Implicit None
        Real (KREAL), Intent (In) :: mu
        Real (KREAL), Intent (In) :: mu0
        
        Real (KREAL)              :: f
        
        Integer                   :: ell
        
        f = ZERO
        do ell = 0, Lcoeff
            f = f + HALF * (2 * ell + 1) * SimpleHorner (x=mu, c=coeff(ell,0:ell)) * SimpleHorner (x=mu0, c=coeff(ell,0:ell))
        end do
        
    End Function
    
    ! Function SlabAngularDistribution (mu, mu0) Result (f)
    !     use BasicMathFunctions
    !     Implicit None
    !     Real (KREAL), Intent (In) :: mu
    !     Real (KREAL), Intent (In) :: mu0
    !     
    !     Real (KREAL)              :: f
    !     
    !     Real (KREAL), Parameter   :: s = 0.01_KREAL
    !     
    !     f = Gaussian (mu * mu0, ONE, s)
    !     
    ! End Function
    
End Module Sources